### ISSUE TITLE
How can i contact you?

### ISSUE THREAD

**Issue by sangeetaaverma** [Vikassm73/MXPlayer#2]
Sir, 

How can I contact you, have some issues regarding configuring the plugin

Please reply

**Comment by Vikassm73** [comment]
You can mail me on vikassm73@gmail.com

**Comment by ManoharOfficial** [comment]
> Sir,
> 
> How can I contact you, have some issues regarding configuring the plugin
> 
> Please reply

Were you able to get the plugin installed? If yes, how?
