### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by ManoharOfficial** [Vikassm73/MXPlayer#3]
I'm very new to kodi and I'm having trouble installing this plugin. I was easily able to install botallen repo and install jiotv. But I just can't seem to figure out how to install this. I tried downloading the zip of this repo and installing it via usb, but not working. Can you guide me through it? Thank you 🙂

**Comment by Vikassm73** [comment]
Please check the installation error. If  script.module.urlresolver is missing then you have to download and install the same before installing this addon (You can easily google and find this script)

**Comment by ManoharOfficial** [comment]
That worked thanks :) I used this https://cthlo.github.io/cthlo-kodi-repo/zips/script.module.urlresolver/
