### ISSUE TITLE
Api help

### ISSUE THREAD

**Issue by venkatmakam** [Vikassm73/MXPlayer#5]
Hi thanks for the wonderful addon. Now i wanted to update the plugin to support video play (atleast currently for my personal use) when i share the link from website or from app through kore (https://github.com/xbmc/Kore) remote. I have already change kore code in my local repo. Now i want to get stream info from the shared link. For this i need to know, 
- is there any api to fetch the details. 
- the list of api supported by mxplayer?

**Comment by Vikassm73** [comment]
I don't understand what you want to achieve. API URL from mxplay is "https://api.mxplay.com" but just by API URL, you won't get all links

**Comment by venkatmakam** [comment]
Hi @Vikassm73 , For ex, if i share a link

**Comment by venkatmakam** [comment]
Hi @Vikassm73, For example how can i get the details of link, https://www.mxplayer.in/show/watch-aashram/chapter-2/triya-charit-online-a27d0095cc646c7b0fde0825ca570f9c from the api?

**Comment by Vikassm73** [comment]
The link for the mentioned episode is 
https://j2apps.s.llnwi.net/video/39daf61cd01716d775827c21f646c4f9/hls/h264_high.m3u8

How to find out:

While playing Press "F12" it will open Dev Tools
Select "Network" from the top row and "XHR" from the third row. Then just check the m3u8 link  (Or in some case MPD link)
from the below list.

Press "Ctrl R" to refresh again if no list appears
